search_tweets_api:
  endpoint: "https://api.twitter.com/2/tweets/search/all"
  consumer_key: "dA6LwKzex4t2GqtYXKtZNQpxV"
  consumer_secret: "tHsh8Vi1CHuOlgToTHggA2m2FPiZf8Lq9rnpmAK1uZa44QeFny"
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAIeESwEAAAAAmaAbhwIaInp4E8H8lQTT0FwbmpE%3DIUU2mQGKdX0jotPFiCwxdYyXZN7PENkqWfs8QfudHG5Q31UxOv"

count_tweets_api:
  endpoint: "https://api.twitter.com/2/tweets/counts/all"
  consumer_key: "dA6LwKzex4t2GqtYXKtZNQpxV"
  consumer_secret: "tHsh8Vi1CHuOlgToTHggA2m2FPiZf8Lq9rnpmAK1uZa44QeFny"
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAIeESwEAAAAAmaAbhwIaInp4E8H8lQTT0FwbmpE%3DIUU2mQGKdX0jotPFiCwxdYyXZN7PENkqWfs8QfudHG5Q31UxOv"
